# Generated by Django 5.0.3 on 2024-04-23 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Fonoaudiologo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=100)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.clinica')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateField(default=django.utils.timezone.now)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.comuna')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.genero')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaFormulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('textoPregunta', models.TextField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.formulario')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.region'),
        ),
        migrations.CreateModel(
            name='RespuestaFormulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('fechaRespuesta', models.DateField(default=django.utils.timezone.now)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.paciente')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.preguntaformulario')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=100)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.genero')),
            ],
        ),
        migrations.CreateModel(
            name='SesionTerapeutica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('actividades', models.TextField()),
                ('tareas', models.TextField()),
                ('estado', models.CharField(max_length=10)),
                ('fonoaudiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.fonoaudiologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.paciente')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaHora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=10)),
                ('fonoaudiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.fonoaudiologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.paciente')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.tutor')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.tutor'),
        ),
    ]
