# Generated by Django 5.0.3 on 2024-05-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_remove_reservahora_paciente_remove_reservahora_tutor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_cita', models.PositiveSmallIntegerField(default=60)),
            ],
        ),
    ]
