# Generated by Django 5.0.3 on 2024-05-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0)),
                ('hora_inicio', models.TimeField(default='09:00')),
                ('hora_fin', models.TimeField(default='18:00')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_trabajo', to='WebApp.fonoaudiologo')),
            ],
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
