# Generated by Django 5.0.3 on 2024-05-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_horastrabajo_delete_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horastrabajo',
            name='hora_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='horastrabajo',
            name='hora_inicio',
            field=models.DateTimeField(),
        ),
    ]
