# Generated by Django 5.0.3 on 2024-05-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_alter_horastrabajo_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservahora',
            name='estado',
            field=models.CharField(default='Reservada', max_length=10),
        ),
    ]
