# Generated by Django 5.0.3 on 2024-05-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_alter_reservahora_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionterapeutica',
            name='estado',
        ),
    ]
