# Generated by Django 5.0.3 on 2024-05-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_remove_sesionterapeutica_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horastrabajo',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes')], default=0),
        ),
    ]
