# Generated by Django 5.0.3 on 2024-06-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_alter_horastrabajo_dia_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIRS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mensaje', models.CharField(choices=[('informacion', 'Información'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
