# Generated by Django 5.0.3 on 2024-06-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_oirs_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='oirs',
            name='respuesta',
            field=models.TextField(blank=True),
        ),
    ]
