# Generated by Django 5.0.3 on 2024-06-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_oirs_fecha_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='antecedentesMedicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
