# Generated by Django 5.0.3 on 2024-06-02 23:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_paciente_antecedentesmedicos_paciente_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='notas',
        ),
        migrations.CreateModel(
            name='NotaPaciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('nota', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.paciente')),
            ],
        ),
    ]
