# Generated by Django 5.0.3 on 2024-06-09 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0019_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha_envio',
            new_name='fechaEnvio',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fonoaudiologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajesEnviados', to='WebApp.fonoaudiologo'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajesRecibidos', to='WebApp.tutor'),
        ),
    ]
