# Generated by Django 5.0.3 on 2024-06-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0020_rename_fecha_envio_mensaje_fechaenvio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
