# Generated by Django 5.0.3 on 2024-06-09 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0021_delete_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=100)),
                ('receptor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('fechaEnvio', models.DateTimeField(default=django.utils.timezone.now)),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
    ]
