# Generated by Django 5.0.3 on 2024-06-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0023_mensaje_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='leido',
            new_name='leidoDos',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leidoUno',
            field=models.BooleanField(default=False),
        ),
    ]
