# Generated by Django 5.0.3 on 2024-06-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0024_rename_leido_mensaje_leidodos_mensaje_leidouno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='apellido',
            new_name='apellidoTutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='email',
            new_name='emailTutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='genero',
            new_name='generoTutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='nombre',
            new_name='nombreTutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='rut',
            new_name='rutTutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='telefono',
            new_name='telefonoTutor',
        ),
    ]
