# Generated by Django 5.0.3 on 2024-04-19 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipoUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.tipousuario'),
            preserve_default=False,
        ),
    ]
